<Project Sdk="Microsoft.NET.Sdk"><ItemGroup><ProjectReference Include="../GameLending.Auth.Application/GameLending.Auth.Application.csproj" /><ProjectReference Include="../../Shared/GameLending.Security/GameLending.Security.csproj" /></ItemGroup><ItemGroup><FrameworkReference Include="Microsoft.AspNetCore.App" /></ItemGroup></Project>
